import type { Metadata } from "next";

import {CartProvider} from "@/components/context/CartContext";
import "./globals.css";
import NavigationResult from "@/components/view/NavigationResult";
import CartModal from "@/components/view/CartModal";
export const metadata: Metadata = {
  title: "ecommerce shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="h-screen box-border relative">
        <CartProvider>
          <div className="p-3">
            <NavigationResult />
            {children}
          </div>
          <CartModal />
        </CartProvider>
      </body>
    </html>
  );
}
